package main

import (
	"8086-sim/logger"
	"errors"
)

/* Mapping of instruction first bytes to the appropriate decoding, disassembling and executing functions */
var InstructionLookup = [...]InstructionFunctions{
	0x00: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x01: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x02: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x03: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x04: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x05: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x06: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x07: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x08: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x09: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x0A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x0B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x0C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x0D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x0E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x0F: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},

	0x10: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x11: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x12: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x13: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x14: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x15: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x16: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x17: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x18: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x19: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x1A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x1B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x1C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x1D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x1E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x1F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x20: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x21: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x22: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x23: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x24: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x25: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x26: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x27: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x28: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x29: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x2A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x2B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x2C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x2D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x2E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x2F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x30: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x31: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x32: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x33: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x34: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x35: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x36: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x37: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x38: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x39: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x3A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x3B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x3C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x3D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x3E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x3F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x40: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x41: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x42: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x43: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x44: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x45: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x46: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x47: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x48: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x49: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x4A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x4B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x4C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x4D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x4E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x4F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x50: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x51: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x52: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x53: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x54: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x55: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x56: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x57: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x58: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x59: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x5A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x5B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x5C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x5D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x5E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x5F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x60: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x61: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x62: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x63: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x64: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x65: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x66: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x67: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x68: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x69: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x6A: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x6B: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x6C: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x6D: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x6E: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0x6F: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},

	0x70: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x71: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x72: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x73: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x74: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x75: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x76: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x77: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x78: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x79: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x7A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x7B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x7C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x7D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x7E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x7F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x80: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x81: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x82: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x83: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x84: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x85: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x86: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x87: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x88: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0x89: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0x8A: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0x8B: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0x8C: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0x8D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x8E: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0x8F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0x90: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x91: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x92: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x93: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x94: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x95: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x96: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x97: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x98: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x99: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x9A: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x9B: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x9C: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x9D: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x9E: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0x9F: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0xA0: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xA1: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xA2: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xA3: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xA4: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xA5: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xA6: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xA7: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xA8: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xA9: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xAA: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xAB: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xAC: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xAD: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xAE: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xAF: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0xB0: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB1: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB2: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB3: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB4: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB5: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB6: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB7: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB8: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xB9: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xBA: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xBB: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xBC: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xBD: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xBE: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xBF: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},

	0xC0: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0xC1: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0xC2: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xC3: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xC4: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xC5: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xC6: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xC7: {DecodeFields: decodeMOV, Disassemble: disassembleMOV, Execute: executeMOV},
	0xC8: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0xC9: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0xCA: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xCB: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xCC: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xCD: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xCE: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xCF: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0xD0: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD1: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD2: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD3: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD4: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD5: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD6: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0xD7: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD8: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xD9: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xDA: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xDB: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xDC: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xDD: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xDE: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xDF: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0xE0: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE1: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE2: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE3: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE4: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE5: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE6: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE7: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE8: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xE9: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xEA: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xEB: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xEC: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xED: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xEE: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xEF: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},

	0xF0: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF1: {DecodeFields: decodeIllegal, Disassemble: disassembleIllegal, Execute: executeIllegal},
	0xF2: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF3: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF4: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF5: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF6: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF7: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF8: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xF9: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xFA: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xFB: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xFC: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xFD: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xFE: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
	0xFF: {DecodeFields: decodeUnimplemented, Disassemble: disassembleUnimplemented, Execute: executeUnimplemented},
}

func decodeUnimplemented(istream *DataStream, instr *Instruction) {
	logger.LogfErr(NAME, "Attempting to decode unimplemented instruction. First byte = 0x%x", instr.FirstByte)
	panic(errors.New("UnimplementedError"))
}

func decodeIllegal(istream *DataStream, instr *Instruction) {
	logger.LogfErr(NAME, "Attempting to decode illegal instruction. First byte = 0x%x", instr.FirstByte)
	panic(errors.New("IllegalInstruction"))
}

func disassembleUnimplemented(instr *Instruction) {
	logger.LogfErr(NAME, "Attempting to dissassemble unimplemented instruction. First byte = 0x%x", instr.FirstByte)
	panic(errors.New("UnimplementedError"))
}

func disassembleIllegal(instr *Instruction) {
	logger.LogfErr(NAME, "Attempting to dissassemble illegal instruction. First byte = 0x%x", instr.FirstByte)
	panic(errors.New("IllegalInstruction"))
}

func executeUnimplemented(instr *Instruction) {
	logger.LogfErr(NAME, "Attempting to execute unimplemented instruction. First byte = 0x%x", instr.FirstByte)
	panic(errors.New("UnimplementedError"))
}

func executeIllegal(instr *Instruction) {
	logger.LogfErr(NAME, "Attempting to execute illegal instruction. First byte = 0x%x", instr.FirstByte)
	panic(errors.New("IllegalInstruction"))
}
